name: address-list.yml

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download
        run: |
          curl -Lo list.txt https://raw.githubusercontent.com/gfwlist/gfwlist/refs/heads/master/list.txt

          echo "new_hash=$(sha256sum list.txt | awk '{print $1}')" >> $GITHUB_ENV

      - name: Load old hash
        run: |
          if [ -f .sha256sum ]; then
            echo "old_hash=$(cat .sha256sum)" >> $GITHUB_ENV
          else
            echo "old_hash=none" >> $GITHUB_ENV
          fi

      - name: Check update
        id: check
        run: |
          if [ "$new_hash" = "$old_hash" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No update"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Updated detected"
          fi

      - name: Generate files
        if: steps.check.outputs.changed == 'true'
        run: |
          set -e

          grep -E '^\||^\|\|' list.txt | \
          grep -v '\*' | \
          grep -v -- '--' | \
          sed -E 's/^\|+//; s/https?:\/\///; s/^[.]+//; s/([a-zA-Z0-9.-]+\.[a-zA-Z]{2,}).*/\1/' | \
          sort -u > address-list.txt

          echo "# MikroTik RouterOS DNS Forward Rules using GFWlist Generator" > address-list.rsc
          echo "# Last modified: $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S') CST" >> address-list.rsc
          echo "# Telegram Messenger https://t.me/hkgali" >> address-list.rsc
          echo "# " >> address-list.rsc
          echo "/ip dns static" >> address-list.rsc
          echo "remove [find address-list=1.1.1.1]" >> address-list.rsc
          sed "s/^/add type=FWD match-subdomain=yes forward-to=1.1.1.1 address-list=1.1.1.1 name=/g" address-list.txt >> address-list.rsc

      - name: Commit changes
        if: steps.check.outputs.changed == 'true'
        run: |
          echo "$new_hash" > .sha256sum

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add address-list.rsc address-list.txt .sha256sum

          git commit -m "Update"
          git push origin main
